version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - ${SOCIAL_DB_PORT}:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${SOCIAL_DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${SOCIAL_DB_ROOT_PASS}
    volumes:
      # - ./mongo-data:/d
      # - ./mongo-entrypoint:/docker-entrypoint-initdb.d:ro
      - mongodb:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodb:
  mongoconfig:
